// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0-devel
// 	protoc        v3.11.4
// source: pb/messages.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	_ "github.com/mwitkow/go-proto-validators"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type LinkState int32

const (
	LinkState_UNKNOWN       LinkState = 0
	LinkState_ACTIVE        LinkState = 1
	LinkState_INACTIVE      LinkState = 2
	LinkState_SYNCHRONIZING LinkState = 3
)

// Enum value maps for LinkState.
var (
	LinkState_name = map[int32]string{
		0: "UNKNOWN",
		1: "ACTIVE",
		2: "INACTIVE",
		3: "SYNCHRONIZING",
	}
	LinkState_value = map[string]int32{
		"UNKNOWN":       0,
		"ACTIVE":        1,
		"INACTIVE":      2,
		"SYNCHRONIZING": 3,
	}
)

func (x LinkState) Enum() *LinkState {
	p := new(LinkState)
	*p = x
	return p
}

func (x LinkState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LinkState) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_messages_proto_enumTypes[0].Descriptor()
}

func (LinkState) Type() protoreflect.EnumType {
	return &file_pb_messages_proto_enumTypes[0]
}

func (x LinkState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LinkState.Descriptor instead.
func (LinkState) EnumDescriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{0}
}

type LinkStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server1 string    `protobuf:"bytes,1,opt,name=server1,proto3" json:"server1,omitempty"`
	Server2 string    `protobuf:"bytes,2,opt,name=server2,proto3" json:"server2,omitempty"`
	Status  LinkState `protobuf:"varint,3,opt,name=status,proto3,enum=jnexus.LinkState" json:"status,omitempty"`
}

func (x *LinkStatus) Reset() {
	*x = LinkStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_messages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LinkStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkStatus) ProtoMessage() {}

func (x *LinkStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pb_messages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkStatus.ProtoReflect.Descriptor instead.
func (*LinkStatus) Descriptor() ([]byte, []int) {
	return file_pb_messages_proto_rawDescGZIP(), []int{0}
}

func (x *LinkStatus) GetServer1() string {
	if x != nil {
		return x.Server1
	}
	return ""
}

func (x *LinkStatus) GetServer2() string {
	if x != nil {
		return x.Server2
	}
	return ""
}

func (x *LinkStatus) GetStatus() LinkState {
	if x != nil {
		return x.Status
	}
	return LinkState_UNKNOWN
}

var File_pb_messages_proto protoreflect.FileDescriptor

var file_pb_messages_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6a, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x1a, 0x36, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6d, 0x77, 0x69, 0x74, 0x6b, 0x6f, 0x77, 0x2f,
	0x67, 0x6f, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x6f, 0x72, 0x73, 0x2f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x83, 0x01, 0x0a, 0x0a, 0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x20, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x31, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x20, 0x01, 0x52, 0x07, 0x73, 0x65, 0x72,
	0x76, 0x65, 0x72, 0x31, 0x12, 0x20, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x32, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x20, 0x01, 0x52, 0x07, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x32, 0x12, 0x31, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x11, 0x2e, 0x6a, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2e,
	0x4c, 0x69, 0x6e, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x42, 0x06, 0xe2, 0xdf, 0x1f, 0x02, 0x20,
	0x01, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x2a, 0x45, 0x0a, 0x09, 0x4c, 0x69, 0x6e,
	0x6b, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57,
	0x4e, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x12,
	0x0c, 0x0a, 0x08, 0x49, 0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x02, 0x12, 0x11, 0x0a,
	0x0d, 0x53, 0x59, 0x4e, 0x43, 0x48, 0x52, 0x4f, 0x4e, 0x49, 0x5a, 0x49, 0x4e, 0x47, 0x10, 0x03,
	0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6a,
	0x66, 0x63, 0x61, 0x6e, 0x74, 0x75, 0x2f, 0x6a, 0x6e, 0x65, 0x78, 0x75, 0x73, 0x2f, 0x70, 0x62,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_messages_proto_rawDescOnce sync.Once
	file_pb_messages_proto_rawDescData = file_pb_messages_proto_rawDesc
)

func file_pb_messages_proto_rawDescGZIP() []byte {
	file_pb_messages_proto_rawDescOnce.Do(func() {
		file_pb_messages_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_messages_proto_rawDescData)
	})
	return file_pb_messages_proto_rawDescData
}

var file_pb_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_messages_proto_goTypes = []interface{}{
	(LinkState)(0),     // 0: jnexus.LinkState
	(*LinkStatus)(nil), // 1: jnexus.LinkStatus
}
var file_pb_messages_proto_depIdxs = []int32{
	0, // 0: jnexus.LinkStatus.status:type_name -> jnexus.LinkState
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pb_messages_proto_init() }
func file_pb_messages_proto_init() {
	if File_pb_messages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_messages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LinkStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_messages_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_messages_proto_goTypes,
		DependencyIndexes: file_pb_messages_proto_depIdxs,
		EnumInfos:         file_pb_messages_proto_enumTypes,
		MessageInfos:      file_pb_messages_proto_msgTypes,
	}.Build()
	File_pb_messages_proto = out.File
	file_pb_messages_proto_rawDesc = nil
	file_pb_messages_proto_goTypes = nil
	file_pb_messages_proto_depIdxs = nil
}
